### ISSUE TITLE
bgrabitmap

### ISSUE THREAD

**Issue by theavege** [Nenirey/LazView#2]
Could you, please, update [BGRABitmap](https://packages.lazarus-ide.org/BGRABitmap.zip) component?

**Comment by Nenirey** [comment]
i am with out time, update it is not hard, can you tray and make a pull?

**Comment by theavege** [comment]
@Nenirey I have [done](https://github.com/Nenirey/LazView/pull/4)

**Comment by Nenirey** [comment]
thanks i merge the changes
